version: "1"
context:
  active-host: "nz387.us1.dbt.com"
  active-project: "70471823432731"
projects:
  - project-name: "Dbt-Hands-On"
    project-id: "70471823432731"
    account-name: "allalionel510@gmail.com"
    account-id: "70471823428691"
    account-host: "nz387.us1.dbt.com"
    token-name: "cloud-cli-b458"
    token-value: "dbtu_RwHRgigjo-KcRLMl2p2TRxH19t38PwK9UTE-1BdsZaDMyWFxt4"
